apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  # below will be same as the env variables present in the .env file while developing locally
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "password"
